name: "CI: docker build"

on: [pull_request]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image (alpine)
      run: docker build . --file Dockerfile.alpine --tag webdevops/go-crond:$(date +%s)
    - name: Build the Docker image (debian)
      run: docker build . --file Dockerfile.debian --tag webdevops/go-crond:$(date +%s)
    - name: Build the Docker image (ubuntu)
      run: docker build . --file Dockerfile.ubuntu --tag webdevops/go-crond:$(date +%s)
